Move check to pr to main to pull-request-checks.yml script

diff --git a/.github/workflows/pull-request-checks.yml b/.github/workflows/pull-request-checks.yml
--- a/.github/workflows/pull-request-checks.yml
+++ b/.github/workflows/pull-request-checks.yml
@@ -3,7 +3,7 @@ on: pull_request
 
 jobs:
   format:
-    name: Check Code Formatting
+    name: Code Formatting
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
@@ -17,7 +17,7 @@ jobs:
         working-directory: functions
 
   lint:
-    name: Check Code Linting
+    name: Code Linting
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
@@ -31,7 +31,7 @@ jobs:
         working-directory: functions
 
   build:
-    name: Check Project Build
+    name: Project Build
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
@@ -45,7 +45,7 @@ jobs:
         working-directory: functions
 
   test:
-    name: Run Tests
+    name: Tests
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
@@ -59,7 +59,7 @@ jobs:
         working-directory: functions
 
   test-emulators:
-    name: Run Tests:Emulators
+    name: Tests:Emulators
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
@@ -71,3 +71,14 @@ jobs:
       - name: Run test:emulators
         run: npm run test:emulators
         working-directory: functions
+
+  validate-pr:
+    name: PR Source for 'main' originates from 'stage'
+    runs-on: ubuntu-latest
+    if: ${{ github.event.pull_request.base.ref == 'main' }}
+    steps:
+      - run: |
+          if [ "${{ github.head_ref }}" != "stage" ]; then
+            echo "Error: PR to main must originate from the 'stage' branch."
+            exit 1
+          fi
